apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: converter
    spec:
      initContainers:
        # 1. Wait for RabbitMQ
        - name: wait-for-rabbitmq
          image: busybox:latest
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: converter-configmap
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: converter-configmap
                  key: RABBITMQ_PORT
          command:
            - sh
            - -c
            - "until nc -zv $RABBITMQ_HOST $RABBITMQ_PORT; do echo 'Waiting for RabbitMQ...'; sleep 2; done;"
        
        # 2. Wait for MongoDB
        - name: wait-for-mongodb
          image: busybox:latest
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: converter-configmap
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: converter-configmap
                  key: MONGODB_PORT
          command:
            - sh
            - -c
            - "until nc -zv $MONGODB_HOST $MONGODB_PORT; do echo 'Waiting for MongoDB...'; sleep 2; done;"

      containers:
        - name: converter
          image: rabeea2100/converter
          # imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /   # or your simple probe endpoint
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 6
