apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: rabeea2100/converter
          # imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /   # or your simple probe endpoint
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 6
