version: "3.2"

dotenv: ['../.env']

tasks:
  kind:01-create-cluster:
    desc: Create a Kubernetes cluster using kind
    cmds:
      - kind create cluster --config kind-config.yaml
    

  kind:02-create-namespace:
    desc: "create k8 name space in the cluster"
    cmds:
      - kubectl create namespace $NAMESPACE
      - kubens $NAMESPACE

  kind:03-delete-namespace:
    desc: "delete all the resources by deleting the name space"
    cmds:
      - kubectl delete ns $NAMESPACE

  kind:04-delete-cluster:
    desc: "Delete a kind Kubernetes cluster"
    cmds:
      - kind delete cluster

  delete-docker-images:
    desc: "Delete the docker images for cleaning"
    cmds:
      - docker rmi $DOCKER_REPO/gateway $DOCKER_REPO/auth $DOCKER_REPO/notification $DOCKER_REPO/converter || true
  
  default:
    desc: "default task placeholder"
    cmds:
      - task -a
    
