apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: auth-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: auth-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker3 # Matches the 3rd worker node in the kind cluster
      containers:
      - name: postgres
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
          - name: POSTGRES_USER
            value: {{ .Values.container.env.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.container.env.password }}
          - name: POSTGRES_DB
            value: {{ .Values.container.env.db }}
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - exec pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc-standard # This must match the name in your PVC manifest
