apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  labels:
    app: auth-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS auth_user (
      id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      email VARCHAR (255) NOT NULL,
      password VARCHAR (255) NOT NULL
    );
    INSERT INTO auth_user (email, password)
    SELECT 'thomasfookins007helby@gmail.com', '123456'
    WHERE NOT EXISTS (SELECT 1 FROM auth_user WHERE email = 'thomasfookins007helby@gmail.com');
    INSERT INTO auth_user (email, password)
    SELECT 'REPLACE_LOGIN_EMAIL', 'REPLACE_LOGIN_PASSWORD'
    WHERE NOT EXISTS (SELECT 1 FROM auth_user WHERE email = 'REPLACE_LOGIN_EMAIL');

  init.sh: |
    #!/bin/sh
    echo "Substituting Helm values into a temporary location..."
    
    # 1. Write the processed SQL to /tmp (which is completely writable)
    sed -e "s|REPLACE_LOGIN_EMAIL|${LOGIN_EMAIL}|g" \
        -e "s|REPLACE_LOGIN_PASSWORD|${LOGIN_PASSWORD}|g" \
        /tmp/init.sql > /tmp/01-init.sql
        
    echo "Executing the processed SQL file..."
    # 2. Run the SQL file directly using the internal psql utility
    psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -f /tmp/01-init.sql
    
    echo "PostgreSQL initialization complete."