version: "3.2"

dotenv: ['../.env']

tasks:
  helm:install-all:
    desc: Install all Helm charts
    deps:
      - helm:install-PostgreSQL
      - helm:install-MongoDB
      - helm:install-RabbitMQ  
      - rabbitmq:create-queues
      - helm:list-all-charts 

  helm:install-PostgreSQL:
    desc: Install PostgreSQL chart
    cmds:
      - echo "Installing PostgreSQL chart"
      - helm upgrade --install postgres ./Postgres --namespace $NAMESPACE --create-namespace

  helm:install-MongoDB:
    desc: Install MongoDB chart
    cmds:
      - echo "Installing MongoDB chart"
      - helm upgrade --install mongodb ./MongoDB --namespace $NAMESPACE --create-namespace

  helm:install-RabbitMQ:
    desc: Install RabbitMQ chart
    cmds:
      - echo "Installing RabbitMQ chart"
      - helm upgrade --install rabbitmq ./RabbitMQ --namespace $NAMESPACE --create-namespace


  rabbitmq:wait:
    desc: "Wait for RabbitMQ to be ready"
    cmds:
      - |
        echo "⏳ Waiting for RabbitMQ..."
        for i in {1..10}; do
          if curl -u guest:guest -s http://$RMQ_HOST:$RMQ_PORT/api/overview > /dev/null; then
            echo "✅ RabbitMQ is ready!"
            exit 0
          fi
          sleep 5
        done
        echo "❌ RabbitMQ not ready"
        exit 1


  rabbitmq:create-queues:
    desc: "Create RabbitMQ queues: video, mp3"
    deps: [rabbitmq:wait]
    cmds:
      - |
        echo "📬 Creating queue 'video'..."
        curl -u guest:guest -X PUT \
        -H "content-type:application/json" \
        http://$RMQ_HOST:$RMQ_PORT/api/queues/%2f/video \
        -d '{"durable":true}'
      - |
        echo "📬 Creating queue 'mp3'..."
        curl -u guest:guest -X PUT \
        -H "content-type:application/json" \
        http://$RMQ_HOST:$RMQ_PORT/api/queues/%2f/mp3 \
        -d '{"durable":true}'

  helm:list-all-charts:
    desc: list all charts
    cmds:
      - echo "listing all charts"
      - helm list -n $NAMESPACE 

  helm:delete-all-charts:
    desc: list all charts
    cmds:
      - echo "deleting all charts"
      - helm list -n $NAMESPACE --short | xargs -L1 helm uninstall

  helm:delete-all-charts-pvcs:
    desc: list all charts
    cmds:
      - echo "deleting all charts"
      - helm list -n $NAMESPACE --short | xargs -L1 helm uninstall
      - echo "deleting all pvcs"
      - kubectl delete pvc --all -n $NAMESPACE



