apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: rabeea2100/notification
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
